从 xpi 包获取 id 和 description
zotero-chinese/zotero-plugins pull request #49
Opened 2023-11-28 14:39 UTC by northword

- 修改 `ts-node` 为 `tsc`，因为 `ts-node` + Node.js 20.x + ESM 似乎不兼容，见 
    - https://github.com/TypeStrong/ts-node/issues/2086
    - https://github.com/TypeStrong/ts-node/issues/2026

- 从 xpi 获取 `plugin.id`，若 `plugin.description` 为空，则从 xpi 补全。

待办：补全 `description`，`install.rdf` 结构居然不一样，需要额外适配一下：

```xml
<?xml version="1.0"?>
<RDF:RDF
    xmlns:em="http://www.mozilla.org/2004/em-rdf#"
    xmlns:NC="http://home.netscape.com/NC-rdf#"
    xmlns:RDF="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <RDF:Description
        RDF:about="urn:mozilla:install-manifest"
        em:id="zotero-format-metadata@northword.cn"
        em:name="Zotero Format Metadata"
        em:version="0.4.4"
        em:type="2"
        em:creator="northword"
        em:description="An addon for Zotero to format item metadata"
        em:homepageURL="https://github.com/northword/zotero-format-metadata#readme"
        em:iconURL="chrome://formatmetadata/content/icons/favicon.png"
        em:optionsURL="chrome://formatmetadata/content/preferences.xul"
        em:updateURL="https://github.com/northword/zotero-format-metadata/releases/latest/download/update.json"
        em:multiprocessCompatible="true"
        em:bootstrap="true">
        <em:targetApplication>
            <Description>
                <em:id>zotero@chnm.gmu.edu</em:id>
                <em:minVersion>5.0</em:minVersion>
                <em:maxVersion>*</em:maxVersion>
            </Description>
        </em:targetApplication>
        <em:targetApplication>
            <Description>
                <em:id>juris-m@juris-m.github.io</em:id>
                <em:minVersion>5.0</em:minVersion>
                <em:maxVersion>*</em:maxVersion>
            </Description>
        </em:targetApplication>
  </RDF:Description>
</RDF:RDF>
```
```xml
<?xml version="1.0" encoding="utf-8"?>
<RDF xmlns="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:em="http://www.mozilla.org/2004/em-rdf#">

    <Description about="urn:mozilla:install-manifest">
        <em:id>keepzotero@yhmtsai</em:id>
        <em:name>KeepZotero</em:name>
        <em:version>0.0.2</em:version>
        <em:type>2</em:type>
        <em:multiprocessCompatible>true</em:multiprocessCompatible>
        <em:optionsURL>chrome://keepzotero/content/options.xul</em:optionsURL>
        <em:updateURL>https://raw.githubusercontent.com/yhmtsai/KeepZotero/master/keepzotero-update.rdf</em:updateURL>
        <em:creator>Yu-Hsiang Mike Tsai</em:creator>

        <em:targetApplication>
            <Description>
                <em:id>zotero@chnm.gmu.edu</em:id>
                <em:minVersion>5.0.0</em:minVersion>
                <em:maxVersion>6.0.*</em:maxVersion>
            </Description>
        </em:targetApplication>
        <em:localized>
            <Description>
                <em:locale>en-US</em:locale>
                <em:name>KeepZotero</em:name>
                <em:description>Keep Zotero in Taskbar</em:description>
            </Description>
        </em:localized>
    </Description>
</RDF>
```

2023-11-29 03:03 UTC, syt2 commented
~~可能对于[zotcard](https://github.com/018/zotcard)的也需要特地适配下~~

> 可供参考的信息
> [firefox XPIInstall](https://github.com/mozilla/gecko-dev/blob/02b4ae79b24aae2346b1338e2bf095a571192061/toolkit/mozapps/extensions/internal/XPIInstall.jsm#L426)
> [firefox addon.py](https://github.com/mozilla/gecko-dev/blob/ac19e2c0d7c09a2deaedbe6afc4cdcf1a4561456/testing/mozbase/mozprofile/mozprofile/addons.py#L213)
> [addon-scraper](https://github.com/syt2/zotero-addons-scraper/blob/master/moz_addons.py)

另外，是否需要考虑对于同时存在z6、z7的插件，开发者使用了不同的id的极端情况？(目前未遇到)

2023-11-29 03:14 UTC, northword commented
> 另外，是否需要考虑对于同时存在z6、z7的插件，开发者使用了不同的id的极端情况？(目前未遇到)

严格的来说，id 变更就意味着已经是两个插件了，所以我觉得可以不用考虑？（主要是现在也没遇到）（我的想法是以从7里面获取到的为主）

2023-11-29 03:27 UTC, syt2 commented
> > 另外，是否需要考虑对于同时存在z6、z7的插件，开发者使用了不同的id的极端情况？(目前未遇到)
> 
> 严格的来说，id 变更就意味着已经是两个插件了，所以我觉得可以不用考虑？（主要是现在也没遇到）（我的想法是以从7里面获取到的为主）

考虑了下也行，如果真遇到了，在plugins内把对应插件拆成两个就行。

2023-11-29 04:11 UTC, northword commented
> > > 另外，是否需要考虑对于同时存在z6、z7的插件，开发者使用了不同的id的极端情况？(目前未遇到)
> > 
> > 
> > 严格的来说，id 变更就意味着已经是两个插件了，所以我觉得可以不用考虑？（主要是现在也没遇到）（我的想法是以从7里面获取到的为主）
> 
> 考虑了下也行，如果真遇到了，在plugins内把对应插件拆成两个就行。

或者就是，id 不放 `PluginInfo.id` ，而是 `PluginInfo.ReleaseInfo.id` ?

2023-11-29 06:06 UTC, syt2 commented
> > > > 另外，是否需要考虑对于同时存在z6、z7的插件，开发者使用了不同的id的极端情况？(目前未遇到)
> > > 
> > > 
> > > 严格的来说，id 变更就意味着已经是两个插件了，所以我觉得可以不用考虑？（主要是现在也没遇到）（我的想法是以从7里面获取到的为主）
> > 
> > 
> > 考虑了下也行，如果真遇到了，在plugins内把对应插件拆成两个就行。
> 
> 或者就是，id 不放 `PluginInfo.id` ，而是 `PluginInfo.ReleaseInfo.id` ?

两种方案都可行吧。
我在[zotero-addons-scraper](https://github.com/syt2/zotero-addons-scraper)里暂时两个都放了，等着这个仓库的格式同步修改脚本和插件去👀

2023-11-29 07:12 UTC, northword commented
```json
[
  {
    "name": "Zotero Format Metadata",
    "repo": "northword/zotero-format-metadata",
    "releases": [
      {
        "targetZoteroVersion": "7",
        "tagName": "latest",
        "currentVersion": "1.6.11",
        "assetId": 135864033,
        "releaseData": "2023-11-16T14:35:35Z",
        "downloadCount": 2245,
        "xpiDownloadUrl": {
          "github": "https://github.com/northword/zotero-format-metadata/releases/download/1.6.11/zotero-format-metadata.xpi",
          "gitee": "https://gitee.com/northword/zotero-plugins/raw/gh-pages/dist/xpi/135864033.xpi",
          "ghProxy": "https://ghproxy.com/?q=https://github.com/northword/zotero-format-metadata/releases/download/1.6.11/zotero-format-metadata.xpi",
          "jsdeliver": "https://cdn.jsdelivr.net/gh/northword/zotero-plugins@gh-pages/dist/xpi/135864033.xpi",
          "kgithub": "https://kkgithub.com/northword/zotero-format-metadata/releases/download/1.6.11/zotero-format-metadata.xpi"
        },
        "id": "zotero-format-metadata@northword.cn"
      },
      {
        "targetZoteroVersion": "6",
        "tagName": "0.4.4",
        "currentVersion": "0.4.4",
        "assetId": 112232528,
        "releaseData": "2023-06-11T06:51:01Z",
        "downloadCount": 12663,
        "xpiDownloadUrl": {
          "github": "https://github.com/northword/zotero-format-metadata/releases/download/0.4.4/zotero-format-metadata.xpi",
          "gitee": "https://gitee.com/northword/zotero-plugins/raw/gh-pages/dist/xpi/112232528.xpi",
          "ghProxy": "https://ghproxy.com/?q=https://github.com/northword/zotero-format-metadata/releases/download/0.4.4/zotero-format-metadata.xpi",
          "jsdeliver": "https://cdn.jsdelivr.net/gh/northword/zotero-plugins@gh-pages/dist/xpi/112232528.xpi",
          "kgithub": "https://kkgithub.com/northword/zotero-format-metadata/releases/download/0.4.4/zotero-format-metadata.xpi"
        },
        "id": "zotero-format-metadata@northword.cn"
      }
    ],
    "description": "Linter for Zotero. An addon for Zotero to format item metadata. Shortcut to set rich text, set journal abbreviations, university places, item languages, etc.",
    "star": 164,
    "watchers": 164,
    "author": {
      "name": "Northword",
      "url": "https://northword.dev",
      "avatar": "https://avatars.githubusercontent.com/u/44738481?v=4"
    }
  },
  {
    "name": "Chartero",
    "repo": "volatile-static/Chartero",
    "releases": [
      {
        "targetZoteroVersion": "6",
        "tagName": "latest",
        "currentVersion": "2.2.0",
        "assetId": 137018637,
        "releaseData": "2023-11-23T05:28:49Z",
        "downloadCount": 1268,
        "xpiDownloadUrl": {
          "github": "https://github.com/volatile-static/Chartero/releases/download/2.2.0/chartero.xpi",
          "gitee": "https://gitee.com/northword/zotero-plugins/raw/gh-pages/dist/xpi/137018637.xpi",
          "ghProxy": "https://ghproxy.com/?q=https://github.com/volatile-static/Chartero/releases/download/2.2.0/chartero.xpi",
          "jsdeliver": "https://cdn.jsdelivr.net/gh/northword/zotero-plugins@gh-pages/dist/xpi/137018637.xpi",
          "kgithub": "https://kkgithub.com/volatile-static/Chartero/releases/download/2.2.0/chartero.xpi"
        },
        "id": "chartero@volatile.static"
      }
    ],
    "description": "Chart in Zotero",
    "star": 233,
    "watchers": 233,
    "author": {
      "name": "volatile-static",
      "url": "https://github.com/volatile-static",
      "avatar": "https://avatars.githubusercontent.com/u/59945270?v=4"
    }
  }
]
```



这样是否可以呢？

另外为了节省传输的体积，默认把 `plugins.json` 给放成了没有缩进的那种，`plugins-debug.json` 是带缩进的易读版本。（或者是易读的`plugins.json`和省流的`plugins.min.json`?）

2023-11-29 07:54 UTC, northword commented
下面是没有考虑不同版本 id 不同的，感觉应该是和 [zotero-addons-scraper](https://github.com/syt2/zotero-addons-scraper) 比较接近的，你看下需不需要修改呢？

另外为了节省传输的体积，增加了一个 `plugins.min.json`。

```json
[
  {
    "name": "Zotero Format Metadata",
    "repo": "northword/zotero-format-metadata",
    "releases": [
      {
        "targetZoteroVersion": "7",
        "tagName": "latest",
        "currentVersion": "1.6.11",
        "assetId": 135864033,
        "releaseData": "2023-11-16T14:35:35Z",
        "downloadCount": 2250,
        "xpiDownloadUrl": {
          "github": "https://github.com/northword/zotero-format-metadata/releases/download/1.6.11/zotero-format-metadata.xpi",
          "gitee": "https://gitee.com/northword/zotero-plugins/raw/gh-pages/dist/xpi/135864033.xpi",
          "ghProxy": "https://ghproxy.com/?q=https://github.com/northword/zotero-format-metadata/releases/download/1.6.11/zotero-format-metadata.xpi",
          "jsdeliver": "https://cdn.jsdelivr.net/gh/northword/zotero-plugins@gh-pages/dist/xpi/135864033.xpi",
          "kgithub": "https://kkgithub.com/northword/zotero-format-metadata/releases/download/1.6.11/zotero-format-metadata.xpi"
        }
      },
      {
        "targetZoteroVersion": "6",
        "tagName": "0.4.4",
        "currentVersion": "0.4.4",
        "assetId": 112232528,
        "releaseData": "2023-06-11T06:51:01Z",
        "downloadCount": 12669,
        "xpiDownloadUrl": {
          "github": "https://github.com/northword/zotero-format-metadata/releases/download/0.4.4/zotero-format-metadata.xpi",
          "gitee": "https://gitee.com/northword/zotero-plugins/raw/gh-pages/dist/xpi/112232528.xpi",
          "ghProxy": "https://ghproxy.com/?q=https://github.com/northword/zotero-format-metadata/releases/download/0.4.4/zotero-format-metadata.xpi",
          "jsdeliver": "https://cdn.jsdelivr.net/gh/northword/zotero-plugins@gh-pages/dist/xpi/112232528.xpi",
          "kgithub": "https://kkgithub.com/northword/zotero-format-metadata/releases/download/0.4.4/zotero-format-metadata.xpi"
        }
      }
    ],
    "description": "Linter for Zotero. An addon for Zotero to format item metadata. Shortcut to set rich text, set journal abbreviations, university places, item languages, etc.",
    "star": 164,
    "watchers": 164,
    "author": {
      "name": "Northword",
      "url": "https://northword.dev",
      "avatar": "https://avatars.githubusercontent.com/u/44738481?v=4"
    },
    "id": "zotero-format-metadata@northword.cn"
  },
  {
    "name": "Chartero",
    "repo": "volatile-static/Chartero",
    "releases": [
      {
        "targetZoteroVersion": "6",
        "tagName": "latest",
        "currentVersion": "2.2.0",
        "assetId": 137018637,
        "releaseData": "2023-11-23T05:28:49Z",
        "downloadCount": 1278,
        "xpiDownloadUrl": {
          "github": "https://github.com/volatile-static/Chartero/releases/download/2.2.0/chartero.xpi",
          "gitee": "https://gitee.com/northword/zotero-plugins/raw/gh-pages/dist/xpi/137018637.xpi",
          "ghProxy": "https://ghproxy.com/?q=https://github.com/volatile-static/Chartero/releases/download/2.2.0/chartero.xpi",
          "jsdeliver": "https://cdn.jsdelivr.net/gh/northword/zotero-plugins@gh-pages/dist/xpi/137018637.xpi",
          "kgithub": "https://kkgithub.com/volatile-static/Chartero/releases/download/2.2.0/chartero.xpi"
        }
      }
    ],
    "description": "Chart in Zotero",
    "star": 233,
    "watchers": 233,
    "author": {
      "name": "volatile-static",
      "url": "https://github.com/volatile-static",
      "avatar": "https://avatars.githubusercontent.com/u/59945270?v=4"
    },
    "id": "chartero@volatile.static"
  }
]
```

2023-11-29 08:45 UTC, syt2 commented
get，没问题

2023-11-29 10:17 UTC, northword commented
CC @volatile-static , 这个 PR 里变更了 ts-node，也许你要看下你那边能不能正常运行（我觉得是没啥问题的）

2023-11-29 13:29 UTC, volatile-static requested changes

2023-11-29 13:29 UTC, volatile-static commented on src/get_plugins_info.ts
> +      plugin.watchers = resp.data.watchers_count;
star和watchers其实是同一个东西。真正的watch数叫subscribers

2023-11-29 13:30 UTC, volatile-static commented
> CC @volatile-static , 这个 PR 里变更了 ts-node，也许你要看下你那边能不能正常运行（我觉得是没啥问题的）

我暂时不需要本地跑了。你那边测着正常就ok

2023-11-29 13:33 UTC, volatile-static commented on src/get_plugins_info.ts
> +      plugin.watchers = resp.data.watchers_count;
https://github.com/zotero-chinese/zotero-plugins/blob/2f842d1f7aa2d42f1d6db2d92cc0317de9c19fe7/src/charts.ts#L62

2023-11-30 00:51 UTC, volatile-static approved these changes

2023-11-30 00:55 UTC, merged